name: CI

on:
    push:
        branches: [main]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        environment: neuralnexus-frontend
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Install dependencies
              run: pnpm install
            - name: Setup Go 1.22.x
              uses: actions/setup-go@v4
              with:
                  go-version: 1.22.x
            - name: Build Go binary
              run: CGO_ENABLED=0 GOOS=linux go build -o ./webserver
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/neuralnexus:frontend
